services:
  - type: web
    name: star-wars-character-explorer-api
    env: node
    plan: free
    buildCommand: npm install && npm run build -w server
    startCommand: npm run start -w server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: COOKIE_SECURE
        value: true
      - key: CLIENT_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
