import { Outlet } from 'react-router-dom';
import { AppHeader } from './AppHeader';

export function AppLayout() {
  return (
    <div className="star-field min-h-screen bg-slate-950 text-slate-100">
      <AppHeader />
      <Outlet />
      <footer className="border-t border-white/10 px-4 py-6 text-center text-sm text-slate-400">
        Character data from SWAPI. Images generated by Picsum seeded placeholders.
      </footer>
    </div>
  );
}
